#!/usr/bin/ruby

class Convert

  def dec_to_hex( decimal )
    sprintf("%x", decimal)
  end

  def hex_to_dec( value  )
    value.to_i(16)
  end

  # take a hex
  #return and rgb
  def css_rgb(hex)
    if /\#?[0-9a-fA-F]{6}/.match(hex)

      if hex.length == 6
        puts "length=6"
        r = hex[0..1]
        puts "r=#{r}"
        g = hex[2..3]
        puts "g=#{g}"
        b = hex[4..5]
        puts "b=#{b}"
      else
        puts "length=7"
        r = hex[1..2]
        g = hex[3..4]
        b = hex[5..6]
      end

      sprintf("%d,%d,%d", hex_to_dec( r ), hex_to_dec( g ), hex_to_dec( b ) )
    else
      "0,0,0"
    end
  end

  def css_hex(red, green, blue)
    sprintf("%02x%02x%02x", red, green, blue)
  end
end


color = ARGV.shift
puts "color=" + color + "\n"

rgb = color.split(",")
puts "rgb length=#{rgb.length}"


con = Convert.new
css_hex = con.css_hex(rgb[0], rgb[1], rgb[2])
css_rgb = con.css_rgb(css_hex)
css_rgb7 = con.css_rgb("#CC66FF")


